// FAQ content.
// Only "Profile & Privacy" → question 1 has an answer in the design.
// Everything marked PLACEHOLDER is filler copy and must be replaced with real content.

export const FAQ_CATEGORIES = [
  {
    id: 'profile-privacy',
    title: 'Profile & Privacy',
    items: [
      {
        q: 'How much of the information I shared during the voice conversation will be used publicly?',
        a: 'Only the content you approve during the editing preview is visible to others. Your voice conversation is never shared publicly.',
      },
      {
        q: 'How are Rivet profiles created?',
        a: 'Only the content you approve during the editing preview is visible to others. Your voice conversation is never shared publicly.',
      },
      {
        q: 'Can I choose which profile details are highlighted?',
        a: 'Only the content you approve during the editing preview is visible to others. Your voice conversation is never shared publicly.',
      },
      {
        q: 'I do not like the image and/or content generated by Rivet.',
        a: 'Only the content you approve during the editing preview is visible to others. Your voice conversation is never shared publicly.',
      },
    ],
  },
  {
    id: 'how-it-works',
    title: 'How Rivet Works',
    items: [
      { q: 'PLACEHOLDER – Who are Matchers?', a: 'Only the content you approve during the editing preview is visible to others. Your voice conversation is never shared publicly.' },
      { q: 'PLACEHOLDER – How does an introduction happen?', a: 'Only the content you approve during the editing preview is visible to others. Your voice conversation is never shared publicly.' },
    ],
  },
  {
    id: 'safety-account',
    title: 'Safety & Account',
    items: [
      { q: 'PLACEHOLDER – How do I report someone?', a: 'Only the content you approve during the editing preview is visible to others. Your voice conversation is never shared publicly.' },
      { q: 'PLACEHOLDER – How do I delete my account?', a: 'Only the content you approve during the editing preview is visible to others. Your voice conversation is never shared publicly.' },
    ],
  },
];
